GET http://localhost:8080/CurrencyExchange-1.0-SNAPSHOT/currencies

###
GET http://localhost:8080/CurrencyExchange-1.0-SNAPSHOT/currency/EUR

###
POST http://localhost:8080/CurrencyExchange-1.0-SNAPSHOT/currencies?name=Australian dollar&code=AUD&sign=$

###
GET http://localhost:8080/CurrencyExchange-1.0-SNAPSHOT/exchangeRates

###
GET http://localhost:8080/CurrencyExchange-1.0-SNAPSHOT/exchangeRate/USDEUR

###
POST http://localhost:8080/CurrencyExchange-1.0-SNAPSHOT/exchangeRates?baseCurrencyCode=USD&targetCurrencyCode=EUR&rate=0.99

###
PATCH http://localhost:8080/CurrencyExchange-1.0-SNAPSHOT/exchangeRates/USDEUR?rate=0.97

###
GET http://localhost:8080/CurrencyExchange-1.0-SNAPSHOT/exchange?from=UAH&to=EUR&amount=39